### ISSUE TITLE
Add support for CommonJS

### ISSUE THREAD

**Issue by mathpere** [Adyen/client-side-encryption#21]
+ remove window global variable
+ remove DOM dependency
+ remove form validation

Or split lib into several lib so that we could use it in any situation.

I cannot use easily this lib with angular.

Best regards.

**Comment by ArnoudAdyen** [comment]
Mathieu,

We are working on splitting out the library in two. One as you know it, another to be a javascript only encryption without DOM dependencies, which you can call with any UI or MVC integration you like.
Because it's a major change it takes some more time testing to make sure everything works as desired.

I will look into adding some commonjs integration, but if it takes too much time, I might skip it for this release, hoping you can work continue using the noDOM implementation.

Best regards

**Comment by bguthrie** [comment]
:+1: This is great to hear. We have rolled our own implementation as we likewise weren't in a position to use this one, but we would _love_ to be able to replace that with a supported version. A simple function that accepts a public key and a data payload and returns an encrypted string would be sufficient.

**Comment by ArnoudAdyen** [comment]
Please have a look at https://github.com/Adyen/CSE-JS where the new version has been released. The commonJS / require support is only superficial as currently still a global `adyen` object is exposed.

I need to figure out how to maintain backwards compatibility with merchants who rely on the `adyen` object but also have a flavour of `define` running. It would be bad if the object wasn't exposed in a flash.

**Comment by mathpere** [comment]
Thanks for your quick support.
I understand your problem. Maybe you could take a look at momentjs lib:
It supports both commonJS support and global exposure.
When used directly from global window, you could print a warning with a further removing.
